import type { Entity } from '../core/types';

export const imageSchema: Entity = {
  name: '_image',
  plural: '_images',
  attributes: [
    {
      name: 'path',
      label: 'Image',
      scope: 'global',
      options: {
        size: 140,
      },
      isEditable: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'imagePreviewField',
      defaultValue: '',
    },
    {
      name: 'originalFilename',
      label: 'Filename',
      scope: 'global',
      options: {
        size: 280,
      },
      isEditable: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      isPrimary: true,
      defaultValue: '',
    },
    {
      name: 'size',
      label: 'Size',
      scope: 'global',
      options: {
        size: 120,
      },
      isEditable: true,
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'width',
      label: 'Width',
      scope: 'global',
      options: {
        size: 80,
      },
      isEditable: true,
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'height',
      label: 'Height',
      scope: 'global',
      options: {
        size: 80,
      },
      isEditable: true,
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'mimeType',
      label: 'Mime Type',
      scope: 'global',
      options: {
        size: 160,
      },
      isEditable: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'lqip',
      label: 'lqip',
      scope: 'global',
      isHidden: true,
      isEditable: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: '_updatedAt',
      label: 'Last Updated',
      scope: 'global',
      options: {
        size: 140,
      },
      isEditable: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
  ],
};
