import type { Entity } from '../core/types';

export const assetSchema: Entity = {
  name: '_asset',
  plural: '_assets',
  display: 'originalFilename',
  menu: {
    hidden: true,
  },
  attributes: [
    {
      name: 'path',
      label: 'Asset',
      scope: 'global',
      options: {
        size: 140,
      },
      dataType: 'string',
      inputType: 'text',
      previewType: 'assetPreviewField',
      defaultValue: '',
    },
    {
      name: 'originalFilename',
      label: 'Filename',
      scope: 'global',
      options: {
        size: 320,
      },
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'size',
      label: 'Size',
      scope: 'global',
      options: {
        size: 120,
      },
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'width',
      label: 'Width',
      scope: 'global',
      options: {
        size: 90,
      },
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'height',
      label: 'Height',
      scope: 'global',
      options: {
        size: 100,
      },
      dataType: 'int',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'mimeType',
      label: 'Mime Type',
      scope: 'global',
      options: {
        size: 160,
      },
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'lqip',
      label: 'lqip',
      scope: 'global',
      hidden: true,
      dataType: 'string',
      inputType: 'text',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: '_updatedAt',
      label: 'Updated At',
      scope: 'global',
      options: {
        size: 220,
      },
      readOnly: true,
      hidden: true,
      dataType: 'datetime',
      inputType: 'datetime',
      previewType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'tags',
      label: 'Tags',
      scope: 'relationship',
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      previewType: 'tags',
      options: {
        size: 300,
      },
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: '_tag',
      },
    },
  ],
};
