name: 'Report a documentation issue'
description: Report an issue with the Flexkit documentation.
title: 'Docs: '
type: Documentation
body:
  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: 'Example: There is incorrect or stale information about the `useAppContext` hook.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://flexkit.io/docs/api-reference/hooks/use-app-context'
    validations:
      required: false
