/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioSplatRouteImport } from './routes/studio/$'
import { Route as ApiFlexkitSplatRouteImport } from './routes/api/flexkit/$'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudioRoute,
} as any)
const ApiFlexkitSplatRoute = ApiFlexkitSplatRouteImport.update({
  id: '/api/flexkit/$',
  path: '/api/flexkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$': typeof StudioSplatRoute
  '/api/flexkit/$': typeof ApiFlexkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$': typeof StudioSplatRoute
  '/api/flexkit/$': typeof ApiFlexkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$': typeof StudioSplatRoute
  '/api/flexkit/$': typeof ApiFlexkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/studio/$' | '/api/flexkit/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/studio/$' | '/api/flexkit/$'
  id: '__root__' | '/' | '/studio' | '/studio/$' | '/api/flexkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiFlexkitSplatRoute: typeof ApiFlexkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/flexkit/$': {
      id: '/api/flexkit/$'
      path: '/api/flexkit/$'
      fullPath: '/api/flexkit/$'
      preLoaderRoute: typeof ApiFlexkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioSplatRoute: typeof StudioSplatRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSplatRoute: StudioSplatRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiFlexkitSplatRoute: ApiFlexkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
