import { defineEntity } from '@flexkit/studio';

export const customerAddresses = defineEntity({
  name: 'customerAddress',
  plural: 'customerAddresses',
  display: 'name',
  menu: {
    hidden: true,
  },
  attributes: [
    {
      name: 'name',
      label: 'Name',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Full name of the recipient',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Name is required' }),
      defaultValue: '',
    },
    {
      name: 'company',
      label: 'Company',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Company name on the address',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'street',
      label: 'Street',
      scope: 'global',
      options: {
        size: 400,
        comment: 'Street address',
      },
      dataType: 'string',
      inputType: 'textarea',
      validation: (z) => z.string().min(1, { error: 'Street is required' }),
      defaultValue: '',
    },
    {
      name: 'postalCode',
      label: 'Postal Code',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Postal or ZIP code',
      },
      dataType: 'string',
      inputType: 'text',
      validation: (z) => z.string().min(1, { error: 'Postal code is required' }),
      defaultValue: '',
    },
    {
      name: 'city',
      label: 'City',
      scope: 'global',
      options: {
        size: 160,
        comment: 'City',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'City is required' }),
      defaultValue: '',
    },
    {
      name: 'phone',
      label: 'Phone',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Phone number at this address',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'taxId',
      label: 'Tax ID',
      scope: 'global',
      options: {
        size: 140,
        comment: 'VAT or tax identification number',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'country',
      label: 'Country',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Country',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'country',
      },
    },
    {
      name: 'type',
      label: 'Address Type',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Whether this address is used for billing or shipping',
        list: [
          { label: 'Billing', value: 'billing' },
          { label: 'Shipping', value: 'shipping' },
        ],
        placeholder: 'Select a type',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: '',
    },
    {
      name: 'customer',
      label: 'Customer',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Customer associated with this address',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'email',
        entity: 'customer',
      },
    },
  ],
});
