import { Tag as TagIcon } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const products = defineEntity({
  name: 'product',
  plural: 'products',
  display: 'name',
  menu: {
    label: 'Products',
    group: 'catalog',
    icon: <TagIcon />,
  },
  groups: [
    { name: 'details', title: 'Details', default: true },
    { name: 'media', title: 'Media' },
    { name: 'pricing', title: 'Pricing' },
    { name: 'catalog', title: 'Catalog' },
    { name: 'inventory', title: 'Inventory' },
    { name: 'content', title: 'Content' },
    { name: 'seo', title: 'SEO' },
  ],
  attributes: [
    {
      name: 'name',
      group: 'details',
      label: 'Name',
      scope: 'local',
      options: {
        size: 260,
        comment: 'The name of the product',
      },
      dataType: 'string', // <-- This is the data type of the attribute, it directly affects how the data is saved in the database
      inputType: 'text', // <-- This affects how the data is displayed in the form (text input, select, WYSIWYG editor, textarea, etc)
      previewType: 'text', // <-- This affects how the data is displayed in the list view (text, image, boolean, WYSIWYG preview, etc)
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Name is required' }),
      defaultValue: '',
    },
    {
      name: 'sku',
      group: 'details',
      label: 'SKU',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Unique SKU identifier',
      },
      dataType: 'string',
      searchable: true,
      unique: true,
      inputType: 'text',
      readOnly: ({ currentUser }) => currentUser?.role === 'viewer',
      validation: (z) => z.string().min(1, { error: 'SKU is required' }),
      defaultValue: '',
    },
    {
      name: 'urlPath',
      group: 'details',
      label: 'URL Path',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Product URL path',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'text',
      hidden: ({ record }) => !record.name,
      defaultValue: '',
    },
    {
      name: 'categoriesPath',
      group: 'details',
      label: 'Categories Path',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Full categories path for the product',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'presentation',
      group: 'details',
      label: 'Presentation',
      scope: 'local',
      options: {
        size: 200,
        comment: 'Product presentation format',
      },
      dataType: 'string',
      searchable: true,
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'description',
      group: 'details',
      label: 'Description',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Full description of the product',
      },
      dataType: 'string',
      inputType: 'editor',
      defaultValue: '',
    },
    {
      name: 'brand',
      group: 'details',
      label: 'Brand',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Brand of the product (i.e. Nike, Adidas, etc)',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'brand',
      },
      // TODO: implement validation for relationship fields
      // validation: (z) => z.string().min(1, { error: 'Brand is required' }),
    },
    {
      name: 'flags',
      group: 'details',
      label: 'Flags',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Product flags (Bio, 100% Natural, etc)',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'flag',
      },
    },
    {
      name: 'category',
      group: 'details',
      label: 'Category',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Each product belongs to one and only one category',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'category',
      },
    },
    {
      name: 'images',
      group: ['media', 'seo'],
      label: 'Images',
      scope: 'relationship',
      options: {
        accept: 'image/*',
        size: 240,
        comment: 'Ordered product gallery images',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'originalFilename',
        entity: '_asset',
      },
    },
    {
      name: 'price',
      group: 'pricing',
      label: 'Price',
      scope: 'local',
      options: {
        size: 130,
        comment: 'The price of the product',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      validation: (z) => z.number().min(1, { error: 'Price is required' }),
      defaultValue: '',
    },
    {
      name: 'pvpr',
      group: 'pricing',
      label: 'PVPR',
      scope: 'local',
      options: {
        size: 130,
        comment: 'Precio de Venta Público Recomendado',
      },
      spaces: ['mkt', 'gtm', 'finance', 'ops', 'cx', 'legal', 'data', 'it'],
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      validation: (z) => z.number().min(1, { error: 'PVPR is required' }),
      defaultValue: '',
    },
    {
      name: 'specialPrice',
      group: 'pricing',
      label: 'Special Price',
      scope: 'local',
      options: {
        size: 130,
        comment: 'Special price of the product',
      },
      dataType: 'float',
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'specialPriceFrom',
      group: 'pricing',
      label: 'Special Price From',
      scope: 'local',
      options: {
        size: 240,
        comment: 'Initial date and time of the special price',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'specialPriceTo',
      group: 'pricing',
      label: 'Special Price To',
      scope: 'local',
      options: {
        size: 240,
        comment: 'Final date and time of the special price',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'metaTitle',
      group: 'seo',
      label: 'Meta Title',
      scope: 'local',
      options: {
        size: 260,
        comment: 'SEO meta title',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'metaDescription',
      group: 'seo',
      label: 'Meta Description',
      scope: 'local',
      options: {
        size: 260,
        comment: 'SEO meta description',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'nutritionFactTable',
      group: 'content',
      label: 'Nutrition Fact Table',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Nutrition facts table content',
      },
      dataType: 'string',
      inputType: 'editor',
      defaultValue: '',
    },
    {
      name: 'flavours',
      group: 'catalog',
      label: 'Flavours',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Product flavours',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'flavour',
      },
    },
    {
      name: 'essences',
      group: 'catalog',
      label: 'Essences',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Product essences',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'essence',
      },
    },
    {
      name: 'mainComponents',
      group: 'catalog',
      label: 'Main Components',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Main product components',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'size',
      group: 'details',
      label: 'Size',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Product size',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'uses',
      group: 'catalog',
      label: 'Uses',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Product uses',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'relationship',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'use',
      },
      defaultValue: '',
    },
    {
      name: 'promoTags',
      group: 'catalog',
      label: 'Promo Tags',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Promotional tags used to group products',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'promoTag',
      },
    },
    {
      name: 'promoCode',
      group: 'catalog',
      label: 'Promo Code',
      scope: 'relationship',
      options: {
        size: 160,
        comment: 'Promotional code used to apply discounts',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'promoCode',
      },
    },
    {
      name: 'unitsInStock',
      group: 'inventory',
      label: 'Units In Stock',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Available stock units',
      },
      dataType: 'int',
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'popularity',
      group: 'inventory',
      label: 'Popularity',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Product popularity score',
      },
      dataType: 'float',
      searchable: false,
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'avgRating',
      group: 'inventory',
      label: 'Average Rating',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Average customer rating',
      },
      dataType: 'float',
      searchable: false,
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'ratingRange',
      group: 'inventory',
      label: 'Rating Range',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Rating range bucket',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'reviews',
      group: 'inventory',
      label: 'Reviews',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Product reviews',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'customerName',
        entity: 'review',
      },
    },
    {
      name: 'contentFormat',
      group: 'details',
      label: 'Content Format',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Product content format',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'contentFormat',
      },
    },
    {
      name: 'storageConditions',
      group: 'content',
      label: 'Storage Conditions',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Product storage conditions',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'composition',
      group: 'content',
      label: 'Composition',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Product composition',
      },
      dataType: 'string',
      inputType: 'editor',
      defaultValue: '',
    },
    {
      name: 'certificate',
      group: 'content',
      label: 'Certificate',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Product certificates',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'buyBoxState',
      group: 'pricing',
      label: 'Buy Box State',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Buy box availability state',
        list: [
          { label: 'Active', value: 'active' },
          { label: 'Main State Not Active', value: 'main-state-not-active' },
          { label: 'Comercial Decatalogued', value: 'comercial-decatalogued' },
          { label: 'Decatalogued', value: 'decatalogued' },
          { label: 'Out of Stock', value: 'out-of-stock' },
          { label: 'No production', value: 'no-production' },
          { label: 'No eligible physical products', value: 'no-eligible-physical-products' },
          { label: 'Manually deactivated', value: 'manually-deactivated' },
        ],
        placeholder: 'Select a state',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'select',
      defaultValue: '',
      validation: (z) => z.string().min(1, { error: 'State is required' }),
    },
    {
      name: 'discountGroup',
      group: 'pricing',
      label: 'Discount Group',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Discount group identifier',
        list: [
          { label: 'None', value: '' },
          { label: '10%', value: '10%' },
          { label: '20%', value: '20%' },
          { label: '30%', value: '30%' },
          { label: '40%', value: '40%' },
          { label: '50%', value: '50%' },
        ],
        placeholder: 'Select a discount group',
      },
      dataType: 'string',
      searchable: false,
      inputType: 'select',
      defaultValue: '',
    },
    {
      name: 'searchName',
      group: 'seo',
      label: 'Search Name',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Search-optimized product name',
      },
      dataType: 'string',
      searchable: true,
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'searchSynonyms',
      group: 'seo',
      label: 'Search Synonyms',
      scope: 'local',
      options: {
        size: 260,
      },
      dataType: 'string',
      searchable: true,
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'searchBenefits',
      group: 'seo',
      label: 'Search Benefits',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Useful in semantic search',
      },
      dataType: 'string',
      searchable: true,
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'searchPlurals',
      group: 'seo',
      label: 'Search Plurals',
      scope: 'local',
      options: {
        size: 260,
        comment: 'Search plural forms',
      },
      dataType: 'string',
      searchable: true,
      inputType: 'textarea',
      defaultValue: '',
    },
  ],
});
