import { Star as StarIcon } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const reviews = defineEntity({
  name: 'review',
  plural: 'reviews',
  menu: {
    label: 'Reviews',
    group: 'ugc',
    icon: <StarIcon />,
  },
  // spaces: ['mkt'],
  attributes: [
    {
      name: 'reviewId',
      label: 'Review ID',
      scope: 'global',
      options: {
        size: 240,
        comment: 'External review identifier',
      },
      dataType: 'string',
      inputType: 'text',
      isUnique: true,
      isSearchable: true,
      validation: (z) => z.string().min(1, { error: 'Review ID is required' }),
      defaultValue: '',
    },
    {
      name: 'createdAt',
      label: 'Created At',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Original review creation timestamp from the source API',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'status',
      label: 'Status',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Moderation status of the review',
        list: [
          { label: 'Pending', value: 'pending' },
          { label: 'Moderated', value: 'moderated' },
          { label: 'Rejected', value: 'rejected' },
        ],
        placeholder: 'Select a status',
      },
      dataType: 'string',
      inputType: 'select',
      previewType: 'reviewStatusPreviewField',
      isSearchable: true,
      defaultValue: '',
    },
    {
      name: 'rating',
      label: 'Rating',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Customer rating from 1 to 5',
      },
      dataType: 'int',
      inputType: 'number',
      previewType: 'ratingPreviewField',
      validation: (z) => z.number().min(1).max(5),
      defaultValue: 5,
    },
    {
      name: 'content',
      label: 'Content',
      scope: 'local',
      options: {
        size: 360,
        comment: 'Review text for the current locale',
      },
      dataType: 'string',
      inputType: 'textarea',
      isPrimary: true,
      isSearchable: true,
      defaultValue: '',
    },
    {
      name: 'customerName',
      label: 'Customer Name',
      scope: 'global',
      options: {
        size: 160,
        comment: 'First name of the customer who wrote the review',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      defaultValue: '',
    },
    {
      name: 'customerLastname',
      label: 'Customer Last Name',
      scope: 'global',
      options: {
        size: 190,
        comment: 'Last name of the customer who wrote the review',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      defaultValue: '',
    },
    {
      name: 'customerEmail',
      label: 'Customer Email',
      scope: 'global',
      options: {
        size: 220,
        comment: 'Email used later to link the review to a customer',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      validation: (z) => z.email({ error: 'Invalid email address' }),
      defaultValue: '',
    },
    {
      name: 'product',
      label: 'Product',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Product this review belongs to',
      },
      dataType: 'string',
      inputType: 'relationship',
      isSearchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'product',
      },
    },
    {
      name: 'brand',
      label: 'Brand',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Brand of the reviewed product',
      },
      dataType: 'string',
      inputType: 'relationship',
      isSearchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'brand',
      },
    },
    {
      name: 'aiScore',
      label: 'AI Score',
      scope: 'global',
      options: {
        size: 140,
        comment: 'AI-generated rating of the review',
      },
      dataType: 'int',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'aiModerationReason',
      label: 'AI Moderation Reason',
      scope: 'global',
      options: {
        size: 240,
        comment: 'Reason returned by AI moderation',
        list: [
          { label: 'None', value: '' },
          { label: 'Appropriate', value: 'appropriate' },
          { label: 'Unjustified Opinion', value: 'unjustified_opinion' },
          { label: 'Price Related', value: 'price_related' },
          { label: 'Medical Claim', value: 'medical_claim' },
          { label: 'Auto Discarded Low Score', value: 'auto_discarded_low_score' },
          { label: 'Auto Discarded Blacklist', value: 'auto_discarded_blacklist' },
          { label: 'Auto Approved', value: 'auto_approved' },
          { label: 'Irrelevant Content', value: 'irrelevant_content' },
          { label: 'Shipping Logistics', value: 'shipping_logistics' },
          { label: 'Not Used Yet', value: 'not_used_yet' },
          { label: 'Store Service', value: 'store_service' },
          { label: 'Expiration Date', value: 'expiry' },
          { label: 'Spam', value: 'spam' },
        ],
        placeholder: 'Select a reason',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: '',
    },
  ],
});
