import { ShoppingCart as ShoppingCartIcon } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const salesOrders = defineEntity({
  name: 'salesOrder',
  plural: 'salesOrders',
  display: 'orderNumber',
  menu: {
    label: 'Sales Orders',
    group: 'operations',
    icon: <ShoppingCartIcon />,
  },
  groups: [
    { name: 'details', title: 'Details', default: true },
    { name: 'items', title: 'Line Items' },
    { name: 'amounts', title: 'Amounts' },
    { name: 'addresses', title: 'Addresses' },
    { name: 'fulfillment', title: 'Fulfillment' },
  ],
  attributes: [
    {
      name: 'orderNumber',
      group: 'details',
      label: 'Order Number',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Human-readable order number',
      },
      dataType: 'string',
      inputType: 'text',
      unique: true,
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Order number is required' }),
      defaultValue: '',
    },
    {
      name: 'orderedAt',
      group: 'details',
      label: 'Ordered At',
      scope: 'global',
      options: {
        size: 180,
        comment: 'Date and time the order was placed',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'channel',
      group: 'details',
      label: 'Channel',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Storefront channel the order was placed on',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'channel',
      },
    },
    {
      name: 'customer',
      group: 'details',
      label: 'Customer',
      scope: 'relationship',
      options: {
        size: 160,
        comment: 'Customer who placed the order',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'email',
        entity: 'customer',
      },
    },
    {
      name: 'status',
      group: 'details',
      label: 'Status',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Lifecycle status of the order',
        list: [
          { label: 'Pending', value: 'pending' },
          { label: 'Processing', value: 'processing' },
          { label: 'Completed', value: 'completed' },
          { label: 'Cancelled', value: 'cancelled' },
          { label: 'Refunded', value: 'refunded' },
        ],
        placeholder: 'Select a status',
      },
      dataType: 'string',
      inputType: 'select',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Status is required' }),
      defaultValue: '',
    },
    {
      name: 'paymentMethod',
      group: 'details',
      label: 'Payment Method',
      scope: 'relationship',
      options: {
        size: 160,
        comment: 'Payment method used for the order',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'paymentMethod',
      },
    },
    {
      name: 'currency',
      group: 'details',
      label: 'Currency',
      scope: 'relationship',
      options: {
        size: 130,
        comment: 'Currency of the order amounts',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'currency',
      },
    },
    {
      name: 'salesOrderItems',
      group: 'items',
      label: 'Line Items',
      scope: 'relationship',
      options: {
        size: 240,
        comment: 'Products purchased on this order; expand to see quantities and prices per line',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'salesOrderItem',
      },
    },
    {
      name: 'itemCount',
      group: 'items',
      label: 'Line Count',
      scope: 'global',
      options: {
        size: 110,
        comment: 'Number of distinct lines on the order',
      },
      dataType: 'int',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'totalQuantity',
      group: 'items',
      label: 'Units',
      scope: 'global',
      options: {
        size: 100,
        comment: 'Total units ordered across all lines',
      },
      dataType: 'int',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'subtotal',
      group: 'amounts',
      label: 'Subtotal',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Sum of all line items including tax, before discounts, shipping and fees',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'discountAmount',
      group: 'amounts',
      label: 'Discount',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Total discount deducted from the subtotal',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'loyaltyDiscount',
      group: 'amounts',
      label: 'Loyalty Discount',
      scope: 'global',
      options: {
        size: 150,
        comment: 'Discount redeemed with loyalty points',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingAmount',
      group: 'amounts',
      label: 'Shipping',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Shipping fee charged to the customer',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'paymentFee',
      group: 'amounts',
      label: 'Payment Fee',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Fee charged for the selected payment method',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'surcharge',
      group: 'amounts',
      label: 'Surcharge',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Additional fee charged on the order',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'donationAmount',
      group: 'amounts',
      label: 'Donation',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Charitable donation added by the customer',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'taxAmount',
      group: 'amounts',
      label: 'Tax',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Tax included in the total',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'total',
      group: 'amounts',
      label: 'Total',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Grand total paid by the customer, including tax',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'exchangeRate',
      group: 'amounts',
      label: 'Exchange Rate',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Exchange rate from the order currency to the base currency',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingName',
      group: 'addresses',
      label: 'Billing Name',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Recipient name on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingCompany',
      group: 'addresses',
      label: 'Billing Company',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Company on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingStreet',
      group: 'addresses',
      label: 'Billing Street',
      scope: 'global',
      options: {
        size: 300,
        comment: 'Street on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'billingPostalCode',
      group: 'addresses',
      label: 'Billing Postal Code',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Postal code on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingCity',
      group: 'addresses',
      label: 'Billing City',
      scope: 'global',
      options: {
        size: 160,
        comment: 'City on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingPhone',
      group: 'addresses',
      label: 'Billing Phone',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Phone on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingTaxId',
      group: 'addresses',
      label: 'Billing Tax ID',
      scope: 'global',
      options: {
        size: 140,
        comment: 'VAT or tax id on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'billingCountry',
      group: 'addresses',
      label: 'Billing Country',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Country on the billing address at order time',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'country',
      },
    },
    {
      name: 'shippingName',
      group: 'addresses',
      label: 'Shipping Name',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Recipient name on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingCompany',
      group: 'addresses',
      label: 'Shipping Company',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Company on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingStreet',
      group: 'addresses',
      label: 'Shipping Street',
      scope: 'global',
      options: {
        size: 300,
        comment: 'Street on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'shippingPostalCode',
      group: 'addresses',
      label: 'Shipping Postal Code',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Postal code on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingCity',
      group: 'addresses',
      label: 'Shipping City',
      scope: 'global',
      options: {
        size: 160,
        comment: 'City on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingPhone',
      group: 'addresses',
      label: 'Shipping Phone',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Phone on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingTaxId',
      group: 'addresses',
      label: 'Shipping Tax ID',
      scope: 'global',
      options: {
        size: 140,
        comment: 'VAT or tax id on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shippingCountry',
      group: 'addresses',
      label: 'Shipping Country',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Country on the shipping address at order time',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'country',
      },
    },
    {
      name: 'fulfillmentStatus',
      group: 'fulfillment',
      label: 'Fulfillment Status',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Logistics status of the order',
        list: [
          { label: 'Pending', value: 'pending' },
          { label: 'Packed', value: 'packed' },
          { label: 'Shipped', value: 'shipped' },
          { label: 'Delivered', value: 'delivered' },
          { label: 'Returned', value: 'returned' },
        ],
        placeholder: 'Select a fulfillment status',
      },
      dataType: 'string',
      inputType: 'select',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'promisedDeliveryAt',
      group: 'fulfillment',
      label: 'Promised Delivery',
      scope: 'global',
      options: {
        size: 180,
        comment: 'Promised delivery date',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'shippedAt',
      group: 'fulfillment',
      label: 'Shipped At',
      scope: 'global',
      options: {
        size: 180,
        comment: 'Date the order was shipped',
      },
      dataType: 'datetime',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'shippingMethod',
      group: 'fulfillment',
      label: 'Shipping Method',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Carrier or shipping service used for the order',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'invoiceUrl',
      group: 'fulfillment',
      label: 'Invoice URL',
      scope: 'global',
      options: {
        size: 260,
        comment: 'URL of the generated invoice',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'invoiceStatus',
      group: 'fulfillment',
      label: 'Invoice Status',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Status of the invoice',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shipments',
      group: 'fulfillment',
      label: 'Shipments',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Warehouse shipments for the order',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'shipmentNumber',
        entity: 'shipment',
      },
    },
  ],
});
