import { ReceiptText as ReceiptTextIcon } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const salesOrderItems = defineEntity({
  name: 'salesOrderItem',
  plural: 'salesOrderItems',
  display: 'name',
  menu: {
    label: 'Order Lines',
    group: 'operations',
    icon: <ReceiptTextIcon />,
  },
  groups: [
    { name: 'line', title: 'Line', default: true },
    { name: 'snapshot', title: 'Product Snapshot' },
    { name: 'fulfillment', title: 'Fulfillment' },
  ],
  attributes: [
    {
      name: 'name',
      group: 'line',
      label: 'Name',
      scope: 'global',
      options: {
        size: 450,
        comment: 'Product name as shown to the customer at the time of the order',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Name is required' }),
      defaultValue: '',
    },
    {
      name: 'sku',
      group: 'line',
      label: 'SKU',
      scope: 'global',
      options: {
        size: 180,
        comment: 'Catalog SKU at the time of the order',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'SKU is required' }),
      defaultValue: '',
    },
    {
      name: 'quantity',
      group: 'line',
      label: 'Quantity',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Units ordered on this line',
      },
      dataType: 'int',
      inputType: 'number',
      validation: (z) => z.number().min(0, { error: 'Quantity is required' }),
      defaultValue: '',
    },
    {
      name: 'unitPrice',
      group: 'line',
      label: 'Unit Price',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Price per unit including tax at the time of the order, before discounts',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'discountAmount',
      group: 'line',
      label: 'Discount',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Discount deducted from this line',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'lineTotal',
      group: 'line',
      label: 'Line Total',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Amount paid for this line including tax: quantity × unit price − discount',
      },
      dataType: 'float',
      inputType: 'number',
      previewType: 'text',
      defaultValue: '',
    },
    {
      name: 'isGift',
      group: 'line',
      label: 'Gift',
      scope: 'global',
      options: {
        size: 90,
        comment: 'Whether this line is a complimentary gift',
      },
      dataType: 'boolean',
      inputType: 'switch',
      defaultValue: '',
    },
    {
      name: 'salesOrder',
      group: 'line',
      label: 'Sales Order',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Order this line belongs to',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'orderNumber',
        entity: 'salesOrder',
      },
    },
    {
      name: 'product',
      group: 'line',
      label: 'Product',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Current catalog product matched by SKU; prices above are the historical ones',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'product',
      },
    },
    {
      name: 'presentation',
      group: 'snapshot',
      label: 'Presentation',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Pack size or presentation at the time of the order',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'brandName',
      group: 'snapshot',
      label: 'Brand Name',
      scope: 'global',
      options: {
        size: 180,
        comment: 'Brand name at the time of the order',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'brand',
      group: 'snapshot',
      label: 'Brand',
      scope: 'relationship',
      options: {
        size: 180,
        comment: 'Catalog brand matched by name when available',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'brand',
      },
    },
    {
      name: 'externalSku',
      group: 'snapshot',
      label: 'External SKU',
      scope: 'global',
      options: {
        size: 150,
        comment: 'Supplier or logistics SKU',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'sourceVariantId',
      group: 'snapshot',
      label: 'Source Variant ID',
      scope: 'global',
      options: {
        size: 240,
        comment: 'Warehouse or physical product identifier from the source system',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'imageUrl',
      group: 'snapshot',
      label: 'Image URL',
      scope: 'global',
      options: {
        size: 240,
        comment: 'Product image URL at the time of the order',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'shipmentItems',
      group: 'fulfillment',
      label: 'Shipment Items',
      scope: 'relationship',
      options: {
        size: 180,
        comment: 'Shipment lines that fulfil this order line',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'shipmentItem',
      },
    },
  ],
});
