import { Truck as TruckIcon } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const shipments = defineEntity({
  name: 'shipment',
  plural: 'shipments',
  display: 'shipmentNumber',
  menu: {
    label: 'Shipments',
    group: 'operations',
    icon: <TruckIcon />,
  },
  attributes: [
    {
      name: 'shipmentNumber',
      label: 'Shipment Number',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Warehouse outbound reference for this shipment',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      validation: (z) => z.string().min(1, { error: 'Shipment number is required' }),
      defaultValue: '',
    },
    {
      name: 'status',
      label: 'Status',
      scope: 'global',
      options: {
        size: 140,
        comment: 'Lifecycle status of the shipment',
        list: [
          { label: 'Pending', value: 'pending' },
          { label: 'Completed', value: 'completed' },
          { label: 'Shipped', value: 'shipped' },
          { label: 'Delivered', value: 'delivered' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
        placeholder: 'Select a status',
      },
      dataType: 'string',
      inputType: 'select',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'shippedAt',
      label: 'Shipped At',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Date the shipment left the warehouse',
      },
      dataType: 'date',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'deliveredAt',
      label: 'Delivered At',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Date the shipment was delivered',
      },
      dataType: 'date',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'trackingNumber',
      label: 'Tracking Number',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Carrier tracking reference',
      },
      dataType: 'string',
      inputType: 'text',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'trackingStatus',
      label: 'Tracking Status',
      scope: 'global',
      options: {
        size: 240,
        comment: 'Latest carrier tracking status',
        list: [
          { label: 'In Transit', value: 'In Transit' },
          { label: 'Out for Delivery', value: 'Out for Delivery' },
          { label: 'Awaiting Collection', value: 'Awaiting Collection' },
          { label: 'Scheduled', value: 'Scheduled' },
          { label: 'Delivery Attempted', value: 'Delivery Attempted' },
          { label: 'Address Issue', value: 'Address Issue' },
          { label: 'Delayed', value: 'Delayed' },
          { label: 'In Customs', value: 'In Customs' },
          { label: 'Delivered', value: 'Delivered' },
          { label: 'Returned', value: 'Returned' },
          { label: 'Cancelled', value: 'Cancelled' },
          { label: 'Damaged', value: 'Damaged' },
          { label: 'Lost', value: 'Lost' },
          { label: 'Destroyed', value: 'Destroyed' },
          { label: 'Unknown', value: 'Unknown' },
        ],
        placeholder: 'Select a tracking status',
      },
      dataType: 'string',
      inputType: 'select',
      searchable: true,
      defaultValue: '',
    },
    {
      name: 'shippingMethod',
      label: 'Shipping Method',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Carrier or shipping method used for this shipment',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'postalCode',
      label: 'Postal Code',
      scope: 'global',
      options: {
        size: 130,
        comment: 'Destination postal code',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'country',
      label: 'Country',
      scope: 'relationship',
      options: {
        size: 150,
        comment: 'Destination country',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'country',
      },
    },
    {
      name: 'salesOrder',
      label: 'Sales Order',
      scope: 'relationship',
      options: {
        size: 160,
        comment: 'Parent sales order',
      },
      dataType: 'string',
      inputType: 'relationship',
      searchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'orderNumber',
        entity: 'salesOrder',
      },
    },
    {
      name: 'shipmentItems',
      label: 'Shipment Items',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Line items included in this shipment',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'shipmentItem',
      },
    },
  ],
});
