import { Building2 } from 'lucide-react';
import { defineEntity } from '@flexkit/studio/ssr';

export const companies = defineEntity({
  name: 'company',
  plural: 'companies',
  menu: {
    label: 'Companies',
    group: 'contacts',
    icon: <Building2 />,
  },
  attributes: [
    {
      name: 'name',
      label: 'Name',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Name of the company',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      isPrimary: true,
      validation: (z) => z.string().min(1, { message: 'Company name is required' }),
      defaultValue: '',
    },
    {
      name: 'industry',
      label: 'Industry',
      scope: 'global',
      options: {
        list: [
          { label: 'Technology', value: 'technology' },
          { label: 'Healthcare', value: 'healthcare' },
          { label: 'Education', value: 'education' },
          { label: 'Finance', value: 'finance' },
          { label: 'Retail', value: 'retail' },
          { label: 'Manufacturing', value: 'manufacturing' },
          { label: 'Other', value: 'other' },
        ],
        size: 180,
        comment: 'Industry of the company',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: '',
    },
    {
      name: 'size',
      label: 'Company Size',
      scope: 'global',
      options: {
        list: [
          { label: '1-10 employees', value: '1-10' },
          { label: '11-50 employees', value: '11-50' },
          { label: '51-200 employees', value: '51-200' },
          { label: '201-500 employees', value: '201-500' },
          { label: '501-1000 employees', value: '501-1000' },
          { label: '1001+ employees', value: '1001+' },
        ],
        size: 180,
        comment: 'Size of the company by employee count',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: '',
    },
    {
      name: 'website',
      label: 'Website',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Website URL of the company',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'description',
      label: 'Description',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Description of the company',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'revenue',
      label: 'Annual Revenue',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Annual revenue of the company',
      },
      dataType: 'float',
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'status',
      label: 'Status',
      scope: 'global',
      options: {
        list: [
          { label: 'Lead', value: 'lead' },
          { label: 'Prospect', value: 'prospect' },
          { label: 'Customer', value: 'customer' },
          { label: 'Churned', value: 'churned' },
        ],
        size: 160,
        comment: 'Current status of the company relationship',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: 'lead',
    },
    {
      name: 'addresses',
      label: 'Addresses',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Addresses of the company',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'address',
      },
    },
    {
      name: 'mainAddress',
      label: 'Main Address',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Main address of the company',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'address',
      },
    },
    {
      name: 'linkedinUrl',
      label: 'LinkedIn URL',
      scope: 'global',
      options: {
        size: 260,
        comment: 'LinkedIn URL of the company',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'logo',
      label: 'Company Logo',
      options: {
        accept: 'image/*',
        size: 160,
        comment: 'Logo of the company',
      },
      dataType: 'image',
      inputType: 'image',
      scope: 'global',
      defaultValue: '',
    },
    {
      name: 'accountManager',
      label: 'Account Manager',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Account Manager who owns this company account',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'firstName',
        entity: 'accountManager',
      },
    },
  ],
});
