import { Users } from 'lucide-react';
import { defineEntity } from '@flexkit/studio/ssr';

export const contacts = defineEntity({
  name: 'contact',
  plural: 'contacts',
  menu: {
    label: 'Contacts',
    group: 'contacts',
    icon: <Users />,
  },
  attributes: [
    {
      name: 'firstName',
      label: 'First Name',
      scope: 'global',
      options: {
        size: 200,
        comment: 'First name of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      validation: (z) => z.string().min(1, { message: 'First name is required' }),
      defaultValue: '',
    },
    {
      name: 'lastName',
      label: 'Last Name',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Last name of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      validation: (z) => z.string().min(1, { message: 'Last name is required' }),
      defaultValue: '',
    },
    {
      name: 'email',
      label: 'Email',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Email address of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      isPrimary: true,
      validation: (z) => z.string().email({ message: 'Invalid email address' }),
      defaultValue: '',
    },
    {
      name: 'phone',
      label: 'Phone',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Phone number of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'mobile',
      label: 'Mobile',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Mobile phone number of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      defaultValue: '',
    },
    {
      name: 'jobTitle',
      label: 'Job Title',
      scope: 'global',
      options: {
        size: 200,
        comment: 'Job title of the contact',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      defaultValue: '',
    },
    {
      name: 'company',
      label: 'Company',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Company this contact belongs to',
      },
      dataType: 'string',
      inputType: 'relationship',
      isSearchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'company',
      },
    },
    {
      name: 'status',
      label: 'Status',
      scope: 'global',
      options: {
        list: [
          { label: 'Lead', value: 'lead' },
          { label: 'Prospect', value: 'prospect' },
          { label: 'Customer', value: 'customer' },
          { label: 'Inactive', value: 'inactive' },
        ],
        size: 160,
        comment: 'Current status of the contact',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: 'lead',
    },
    {
      name: 'source',
      label: 'Source',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Source of the contact',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'leadSource',
      },
    },
    {
      name: 'lastContactedAt',
      label: 'Last Contacted',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Date when the contact was last contacted',
      },
      dataType: 'date',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'notes',
      label: 'Notes',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Notes about the contact',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'addresses',
      label: 'Addresses',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Addresses of the contact',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'address',
      },
    },
    {
      name: 'tags',
      label: 'Tags',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Tags associated with this contact',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'tag',
      },
    },
    {
      name: 'image',
      label: 'Profile Picture',
      options: {
        accept: 'image/*',
        size: 160,
        comment: 'Profile picture of the contact',
      },
      dataType: 'image',
      inputType: 'image',
      scope: 'global',
      defaultValue: '',
    },
    {
      name: 'accountManager',
      label: 'Account Manager',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Account Manager who owns this contact',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'firstName',
        entity: 'accountManager',
      },
    },
  ],
});
