import { BarChart4 } from 'lucide-react';
import { defineEntity } from '@flexkit/studio';

export const deals = defineEntity({
  name: 'deal',
  plural: 'deals',
  menu: {
    label: 'Deals',
    group: 'sales',
    icon: <BarChart4 />,
  },
  attributes: [
    {
      name: 'name',
      label: 'Deal Name',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Name of the deal',
      },
      dataType: 'string',
      inputType: 'text',
      isSearchable: true,
      isPrimary: true,
      validation: (z) => z.string().min(1, { message: 'Deal name is required' }),
      defaultValue: '',
    },
    {
      name: 'company',
      label: 'Company',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Company associated with this deal',
      },
      dataType: 'string',
      inputType: 'relationship',
      isSearchable: true,
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'company',
      },
      validation: (z) => z.string().min(1, { message: 'Company is required' }),
    },
    {
      name: 'contacts',
      label: 'Contacts',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Contacts associated with this deal',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'firstName',
        entity: 'contact',
      },
    },
    {
      name: 'value',
      label: 'Deal Value',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Monetary value of the deal',
      },
      dataType: 'float',
      inputType: 'number',
      validation: (z) => z.number().min(0, { message: 'Value must be a positive number' }),
      defaultValue: '',
    },
    {
      name: 'currency',
      label: 'Currency',
      scope: 'relationship',
      options: {
        size: 120,
        comment: 'Currency of the deal value',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'code',
        entity: 'currency',
      },
    },
    {
      name: 'stage',
      label: 'Pipeline Stage',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Current stage in the sales pipeline',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'pipelineStage',
      },
      validation: (z) => z.string().min(1, { message: 'Pipeline stage is required' }),
    },
    {
      name: 'probability',
      label: 'Probability (%)',
      scope: 'global',
      options: {
        size: 120,
        comment: 'Probability of winning the deal (percentage)',
        min: 0,
        max: 100,
      },
      dataType: 'float',
      inputType: 'number',
      defaultValue: '',
    },
    {
      name: 'expectedCloseDate',
      label: 'Expected Close Date',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Expected date when the deal will close',
      },
      dataType: 'date',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'actualCloseDate',
      label: 'Actual Close Date',
      scope: 'global',
      options: {
        size: 160,
        comment: 'Actual date when the deal closed',
      },
      dataType: 'date',
      inputType: 'datetime',
      defaultValue: '',
    },
    {
      name: 'source',
      label: 'Lead Source',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Source of the deal lead',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'name',
        entity: 'leadSource',
      },
    },
    {
      name: 'accountManagers',
      label: 'Account Manager',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Account Manager who owns this deal',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'single',
        field: 'firstName',
        entity: 'accountManager',
      },
      validation: (z) => z.string().min(1, { message: 'Deal owner is required' }),
    },
    {
      name: 'products',
      label: 'Products',
      scope: 'relationship',
      options: {
        size: 260,
        comment: 'Products associated with this deal',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'product',
      },
    },
    {
      name: 'description',
      label: 'Description',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Description of the deal',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'priority',
      label: 'Priority',
      scope: 'global',
      options: {
        list: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
        ],
        size: 120,
        comment: 'Priority level of the deal',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: 'medium',
    },
    {
      name: 'status',
      label: 'Status',
      scope: 'global',
      options: {
        list: [
          { label: 'Open', value: 'open' },
          { label: 'Won', value: 'won' },
          { label: 'Lost', value: 'lost' },
        ],
        size: 120,
        comment: 'Current status of the deal',
      },
      dataType: 'string',
      inputType: 'select',
      defaultValue: 'open',
    },
    {
      name: 'lostReason',
      label: 'Lost Reason',
      scope: 'global',
      options: {
        size: 260,
        comment: 'Reason why the deal was lost (if applicable)',
      },
      dataType: 'string',
      inputType: 'textarea',
      defaultValue: '',
    },
    {
      name: 'tags',
      label: 'Tags',
      scope: 'relationship',
      options: {
        size: 200,
        comment: 'Tags associated with this deal',
      },
      dataType: 'string',
      inputType: 'relationship',
      defaultValue: '',
      relationship: {
        mode: 'multiple',
        field: 'name',
        entity: 'tag',
      },
    },
  ],
});
